Repository interuss/dss, pull requests merged in 2018-11, with the labels that each got.

#44 Add in-grid UVR support
  assets/swaggerhub_api.yaml
  datanode/src/format_utils.py
  datanode/src/storage_api.py
  datanode/src/storage_api_test.py
  datanode/src/storage_interface.py
  datanode/src/storage_interface_test.py
  datanode/src/test_utils.py
  datanode/src/uss_metadata.py
  datanode/src/uvrs.py
Labels: cla: yes

#46 Fix UVR data carriage
  datanode/src/storage_api.py
  datanode/src/storage_api_test.py
Labels: cla: yes

#47 Add real-time monitoring tools
  datanode/tools/client_tools.py
  datanode/tools/get_token
  datanode/tools/monitor
  datanode/tools/report
  datanode/tools/reports.py
Labels: cla: yes

#48 Only iterate through JSON 'uvr' field if it is present
  datanode/src/storage_api.py
  datanode/src/uss_metadata.py
Labels: cla: yes

#51 Implement public portal API changes
  datanode/src/storage_api.py
  datanode/src/storage_api_test.py
  datanode/src/storage_interface.py
  datanode/src/storage_interface_test.py
  datanode/src/uss_metadata.py
Labels: cla: yes, public portal

#52 Minor fix on #65
  README.md
Labels: cla: yes

#55 Update UVR schema and validate required fields
  datanode/src/storage_api.py
  datanode/src/storage_api_test.py
  datanode/src/storage_interface.py
  datanode/src/test_utils.py
  datanode/src/uvrs.py
Labels: TCL4, cla: yes

#53 Add auth server
  authserver/docker/Dockerfile_authreverseproxy
  authserver/docker/Dockerfile_authserver
  authserver/docker/README.md
  authserver/docker/docker-compose.yaml
  authserver/docker/nginx_entrypoint.sh
  authserver/src/auth_server.py
  authserver/src/auth_server_test.py
Labels: cla: yes
